### PR TITLE
Minor fixes (types and validation)

### PR DESCRIPTION
**Pull request by robertkiel**
Fixes:

**as defined in Node.JS**
```
NodeAddress.port: number
```
instead of 
```
NodeAddress.port: string
```
 
**as implemented in index.js**
```
.getPeerId(): string | null
```
instead of
```
.getPeerId(): string
```

**proper error for .toOptions()**
```
Multiaddr('/p2p/QmcgpsyWgH8Y8ajJz1Cu72KnS5uo2Aa2LpzU7kinSupNKC').toOptions() // Error('Invalid address family')
```
instead of
```
Multiaddr('/p2p/QmcgpsyWgH8Y8ajJz1Cu72KnS5uo2Aa2LpzU7kinSupNKC').toOptions() => {
  family: 'ip6'
  address: 'QmcgpsyWgH8Y8ajJz1Cu72KnS5uo2Aa2LpzU7kinSupNKC'
}
```

### CODE REVIEW

**Comment by vasco-santos** [comment]
Thanks for the PR @robertkiel 

We are doing a major revamp to generate type declaration files from jsdoc. This is being worked in https://github.com/multiformats/js-multiaddr/pull/159, which makes this PR redundant at this point.

**Comment by robertkiel** [comment]
> Thanks for the PR @robertkiel
> 
> We are doing a major revamp to generate type declaration files from jsdoc. This is being worked in #159, which makes this PR redundant at this point.

Sounds good :+1: my suggestions are more related to inconveniences resp. incompatibilities with NodeJS and IP addresses.

**Comment by vasco-santos** [comment]
I see, so would you mind adding them on top of #159 in a new PR if they are still an issue on that PR?

**Comment by robertkiel** [comment]
Sounds good. Could you give me an estimate when how close you are? Will create a PR if necessary once you are mostly done.

**Comment by vasco-santos** [comment]
Thanks, I hope soon. @hugomrdias can you let us know in this PR once #159 gets merged?

**Pull request closed without merging**
