### PR TITLE
fix UDP code

### LINKED ISSUE #17: Enable circle-ci
takes like 3 seconds :D

### LINKED ISSUE #72: UDP code is incorrect
The code was changed in https://github.com/multiformats/multicodec/pull/16 but that change was never reflected in https://github.com/multiformats/multiaddr.

### PR DESCRIPTION
**Pull request by Stebalien**
fixes #72

### CODE REVIEW

**Comment by richardschneider** [comment]
Why has the code changed from 17 to 273?  Isn't this a major breaking change.

**Comment by Stebalien** [comment]
This *was* a breaking change but the actual change happened in https://github.com/multiformats/multicodec/pull/16. Unfortunately, the change was never propagated to js-multiaddr (or multiformats/multiaddr...). However, go-multiaddr *was* updated.

**Comment by vmx** [comment]
I agree that this is a breaking change. That information should be part of the commit message so that it ends up in the changelog (see the [JS Coding Guidelines](https://github.com/ipfs/community/blob/16ab3e72c3091f214e24862fc334993e8930eee0/CONTRIBUTING_JS.md#footer) for more information).

Possible commit message:

```
fix: change UDP code

BREAKING CHANGE: The UDP code was changed in the multicodec table

The UDP code is now `273` instead of `17`. For the full discussion of this change
please see https://github.com/multiformats/multicodec/pull/16.

Fixes #17.
```

**Comment by daviddias** [comment]
Adding a ping to @victorb to review as the Lead Maintainer of this module -- https://github.com/multiformats/js-multiaddr#lead-maintainer

Thanks for reviewing and pointing to the Contributing guidelines as a source on how to complete this PR, @vmx 👏🏽👏🏽👏🏽

**Comment by victorb** [comment]
CI is failing here as the test-cases haven't been updated. See the failures here: https://ci.ipfs.team/blue/organizations/jenkins/Multiformats%2Fjs-multiaddr/detail/PR-73/1/tests

**Comment by Stebalien** [comment]
Seriously?

>    49:7  warning  Unexpected use of continue statement  no-continue
...
>   341:1   warning  Unexpected 'todo' comment                   no-warning-comments

**Comment by victorb** [comment]
Great, thanks!

**Comment by victorb** [comment]
[js-multiaddr@6.0.0 has now been released!](https://github.com/multiformats/js-multiaddr/blob/594e1334d042932de916da8e9c79fa61af0d0c31/CHANGELOG.md#600-2018-11-28)

**Comment by daviddias** [comment]
@victorb did you completely ignore @vmx's indication? https://github.com/multiformats/js-multiaddr/pull/73#issuecomment-442388683

**Comment by Stebalien** [comment]
@daviddias I fixed the commit message before this was merged.

**Comment by vmx** [comment]
@daviddias You have to look at the commit history and you'll find https://github.com/multiformats/js-multiaddr/commit/e8c3d7dd7fbd6490d261a3011e13deeb0cf59f39, which contains the proper "breaking change"  part (which also shows up in the changelog).

The GitHub message links to the merge commit, you would need to click through it's parents.

**Comment by daviddias** [comment]
I see. I looked through the commit history but I looked at @victorb commits and not @Stebalien, my bad.

**Pull request merged**
