### PR TITLE
chore: Make @jacobheun the lead maintainer

### PR DESCRIPTION
**Pull request by vmx**
I think it would make sense to hand the lead maintainership over to someone from the libp2p team, I propose @jacobheun.

What do you think @victorb?

Once approved my @victorb (current lead maintainer) and @daviddias (tech lead) I'll add jacob as maintainer to npm and will remove myself.

### CODE REVIEW

**Comment by vmx** [comment]
This was triggered by: https://github.com/multiformats/js-multiaddr/pull/78#issuecomment-453876124

**Comment by vmx** [comment]
@daviddias Tech lead, please approve :)

**Comment by daviddias** [comment]
Meanwhile, already gave @jacobheun publish perms

**Comment by vmx** [comment]
Good catch @daviddias, it's fixed now.

**Pull request merged**
