### PR TITLE
Fix p2p addrs

### PR DESCRIPTION
**Pull request by diasdavid**
part of https://github.com/ipfs/js-ipfs/issues/981

### CODE REVIEW

**Comment by mkg20001** [comment]
p2p-websocket**s**-star. Why the s?

**Comment by diasdavid** [comment]
Yeah, just realized you called it `websocket-star` when the repo was moved. We are fine with either, I picked websockets-star with the _s_ because we always say the "WebSockets Transport" (for some reason). Wanna PR to remove it?

**Comment by mkg20001** [comment]
Yup

**Comment by mkg20001** [comment]
PR: #46

**Pull request merged**
