### PR TITLE
[WIP] Awesome API Documentation

### PR DESCRIPTION
**Pull request by dignifiedquire**
Ref https://github.com/ipfs/js-ipfs/issues/615

### CODE REVIEW

**Comment by VictorBjelkholm** [comment]
@dignifiedquire should be ok now, please leave feedback :)

Preview: https://victorbjelkholm.github.io/js-multiaddr/

**Comment by dignifiedquire** [comment]
Cool stuff @VictorBjelkholm, not super happy about this though:

screen shot 2016-12-09 at 13 40 20

which is not your fault, but this needs some work in the theme/parsing

**Comment by dignifiedquire** [comment]
So it turns out the general notion of how to document this in jsdoc are one of the two following

## Complex

Allows for individual property descriptions, but adds another section

```js
/**
 * @typedef {Object} Protocols
 * @param {Array}  table
 * @param {Object} names
 * @param  {Object} codes - protocols
 */
/**
 * @returns {Protocols}
 */
```

## Simple

Does not allow for description of individual properties

```js
/**
 * @returns {{table: Array, names: Object, codes: Object}}
 */
```

**Comment by VictorBjelkholm** [comment]
@diasdavid 
>  diasdavid requested a review from VictorBjelkholm 5 hours ago
PR is from me, might be better for @dignifiedquire or you to review it :)

**Comment by dignifiedquire** [comment]
@VictorBjelkholm could you update the return values to use one of the two variants I listed above please?

**Comment by VictorBjelkholm** [comment]
@dignifiedquire thanks, applied where applicable

**Comment by dignifiedquire** [comment]
LGTM

**Pull request merged**
