### PR TITLE
Feat/dnsaddr

### PR DESCRIPTION
**Pull request by dryajov**
Renaming /dns to /dnsaddr to conform with go

### CODE REVIEW

**Comment by diasdavid** [comment]
Why this change @lgierth @whyrusleeping ??

**Comment by lgierth** [comment]
Oh I see now what you meant @dryajov. The `/dns` in the protocol codes table is definitely correct as it is.

@diasdavid the context is that @dryajov noticed that there's `/dnsaddr` in go-ipfs, but not in js-ipfs, and that there's `/dns` in js-ipfs but not anywhere else.

I think I'd propose:
- Remove `/dns` -- we haven't defined `/dns`, the only thing we've done for it is reserve its protocol code in the table.
- Add `/dnsaddr`and make it a "resolvable" protocol. You *will* encounter `/dnsaddr` addresses and it'd be good to regard them as valid.

I see that `Multiaddr.resolve()` doesn't really do anything yet. Maybe [go-multiaddr-dns](https://github.com/multiformats/go-multiaddr-dns) can serve as inspiration.

**Comment by diasdavid** [comment]
@lgierth I'm not understanding what is the real difference between `/dns` and `/dnsaddr` other than it seems that go-ipfs shipped /dnsaddr in the latest version, although it was not present on the table.

**Comment by lgierth** [comment]
I'm not understanding what `/dns` is supposed to do -- we never defined what it'd do. We only defined `/dns4` and `/dns6` (and `/dnsaddr`)

**Comment by diasdavid** [comment]
Ack. Seems I never got the packet about /dnsaddr but yeah I remember we being unsure about /dns.

Looks good to me know. Merging and releasing. Thanks @lgierth and @dryajov :)

**Pull request merged**
